### ISSUE TITLE
RX888

### ISSUE THREAD

**Issue by HB9RYZ** [Steven9101/PhantomSDR-Plus#2]
Hello All
I'm using this start:
rx888_stream -f ../rx888_stream/SDDC_FX3.img -s 64000000 -g 90 -m low -d --pga -o - | build/spectrumserver --config config.toml

And the config.toml in your sample.
https://github.com/Steven9101/PhantomSDR-Plus/wiki/Config-examples

**But I have just an empty and black waterfall.**

Hardware is HP PC EliteDesk 800 G2 with Ubuntu Desktop 20.04.22 TLS

73 de HB9RYZ
Wolfgang

**Comment by Steven9101** [comment]
Hi Wolfgang, can you send a screenshot of the software log? Like when you start it? Also do you use an RX888 normal or RX888 MKii

**Comment by Steven9101** [comment]
```
rx888_stream -f ./rx888_stream/SDDC_FX3.img -s 64000000 -g 90 -m low -d --pga -o - | build/spectrumserver --config config.toml
```

You could also try this aswell because i think the install script i made puts it in the same folder as PhantomSDR-Plus

**Comment by HB9RYZ** [comment]
Hi Steven
I have an **RX888 MKII**

And used this command to start the stream:
**rx888_stream -f ../rx888_stream/SDDC_FX3.img -s 64000000 -g 90 -m low -d --pga -o - | build/spectrumserver --config config.toml**

And this my config.toml

[server]
port=1337 # Server port
html_root="frontend/dist/" # HTML files to be hosted
otherusers=1 # Send where other users are listening, 0 to disable
threads=1

[websdr]
register_online=false # If the SDR should be registered on https://sdr-list.xyz then put it to true
name="HB9RYZ" # Name that is shown on https://sdr-list.xyz
antenna="X ONE active Dipole Stampfl” # Antenna that is shown on https://sdr-list.xyz
grid_locator="JN47FE" # 4 or 6 length Grid Locatlr shown on https://sdr-list.xyz and for the Distance of FT8 Signals
hostname="" # If you use ddns or something to host with a domain enter it here for https://sdr-list.xyz

[limits]
audio=100
waterfall=100
events=100

[input]
sps=64000000 # Input Sample Rate
fft_size=4194304 # FFT bins
brightness_offset=0 # Waterfall brightness offset. Reduce to negative if you see black regions in the waterfall
fft_threads=10 # FFT threads
frequency=0 # Baseband frequency
signal="real" # real or iq
accelerator="none" # Accelerator: none, cuda, opencl
audio_sps=48000 # Audio Sample Rate
audio_compression="flac" # flac or opus
waterfall_size=2048
waterfall_compression="zstd" # zstd or av1
smeter_offset=0

[input.driver]
name="stdin" # Driver name
format="s16" # Sample format: u8, s8, u16, s16, u32, s32, f32, f64

[input.defaults]
frequency=5505000 # Default frequency to show user
modulation="USB" # Default modulation

73' Wolfgang

**Comment by HB9RYZ** [comment]
Attached the screenshot if I start the stream and the screenshot of the website (waterfall)
![Screenshot RX888 Waterfall HB9RYZ](https://github.com/Steven9101/PhantomSDR-Plus/assets/70882661/8fb9dbe7-e938-4446-a887-966216501a53)


![Screenshot RX888 start HB9RYZ](https://github.com/Steven9101/PhantomSDR-Plus/assets/70882661/13a09270-75ea-478d-bd84-ddb6fe3c1822)

**Comment by HB9RYZ** [comment]
Its working now :-)

I saw, that your start command was:
rx888_stream -f ./rx888_stream/SDDC_FX3.img -s 64000000 -g 90 -m low -d --pga -o - | build/spectrumserver --config config.toml

and my start command was 
rx888_stream -f **..**/rx888_stream/SDDC_FX3.img ....

![image](https://github.com/Steven9101/PhantomSDR-Plus/assets/70882661/577dc7c1-3a7f-4d99-8313-d34a4e893987)

73 Wolfgang

**Comment by HB9RYZ** [comment]
![image](https://github.com/Steven9101/PhantomSDR-Plus/assets/70882661/6ad18ed1-4424-457e-be1a-ce92d657c6cf)

**Comment by HB9RYZ** [comment]
High CPU load

![image](https://github.com/Steven9101/PhantomSDR-Plus/assets/70882661/6fc47d77-6a42-4c83-90a1-9dfa8d782389)

**Comment by HB9RYZ** [comment]
Here a picture of the current setup with the RX888 MKII and the live stream here https://sdr-list.xyz/

![PhantomPlus SDR with RX888 MKII de HB9RYZ](https://github.com/Steven9101/PhantomSDR-Plus/assets/70882661/b908f381-5b43-4061-8f7c-b2b28688ec1e)

73 de HB9RYZ
Wolfgang

**Comment by Steven9101** [comment]
Hi Wolfgang, yes most likely you need more processing power. You can also use a gpu for this but in this pc it makes no sense because the graphics unit is on the cpu and therefore it would only make the cpu hotter and give it more load. I think it should be fine on the CPU as more users wont really increase it.

**Comment by Steven9101** [comment]
I think it shouldn’t stutter aslong as cpu stays on 80% so thats fine for some users.

**Comment by Steven9101** [comment]
For size and some other things im currently thinking. On aachen websdr i tried an alternative twente like layout. Do you like this more?

**Comment by HB9RYZ** [comment]
Hello Steven
Yes, I like the Aachen look and feel. What kind of PC or CPU Power is used with the Aachen WebSDR?
How can I get the Aachen GUI?
Gianni HB3XDC gave me some hints to optimize the CPU Power on my HP Intel PC.
73' Wolfgang

**Comment by HB9RYZ** [comment]
What about the FT8 Decoding optione. If I go to a FT8 freq. and press on FT8, nothing will happen.

**Comment by HB9RYZ** [comment]
How can I optimize the Intel CPU performace. What about the parameter **[accelerator="none" # Accelerator: none, cuda, opencl]** in the config.toml file?

I have at the moment **"none"**.

This is the current CPU Load:
![image](https://github.com/Steven9101/PhantomSDR-Plus/assets/70882661/d0b51bb1-d104-483c-b4d6-f014fa7a0447)

**Comment by Steven9101** [comment]
You have to install opencl etc, i can help you later. Otherwise you can maybe ask HB3XDC because im not home yet. The gui will be released soon

**Comment by Steven9101** [comment]
For ft8 put audio sample rate from 48000 to 12000

**Comment by Steven9101** [comment]
The aachen websdr uses ryzen 5 2600 and rx580 both can handle the rx888 mkii at 64mhz. Both the rx580 and the ryzen 5 2600. but i mainly only use the cpu even tho the gpu is faster i think.

**Comment by HB9RYZ** [comment]
ok, I already installed opencl with:

sudo apt update
sudo apt install intel-opencl-icd

Will do some more tests this afternoon.

**Comment by HB9RYZ** [comment]
no decodes with FT8 - and I changed audio from 48000 to 12000

![image](https://github.com/Steven9101/PhantomSDR-Plus/assets/70882661/4db62306-855f-43a6-8faf-dcae84393740)

**Comment by HB9RYZ** [comment]
I installed opencl but I still get this error if start the websdr server
config.toml --> accelerator="opencl" 

![image](https://github.com/Steven9101/PhantomSDR-Plus/assets/70882661/7539e36c-c16b-44eb-8b1d-08a301527dca)

**Comment by Steven9101** [comment]
Should work with 12000 after restart, for gpu you need to install the intel you already installed and

apt install libclfft-dev

then save your config somewhere else and just delete the folder and rebuild phantomsdr plus with install script again. It will work then.

**Comment by HB9RYZ** [comment]
I did a new installation of Phantom SDR Plus (run install.sh) but now it's not working anymore.
Even with accelator "none" or "opencl".

![image](https://github.com/Steven9101/PhantomSDR-Plus/assets/70882661/7b8ddc59-4d93-4607-a5bd-bec9ad18bde0)

I'm not a Linux expert - so it is very hard for me to undastand all these error messages.
I would expect a script file, which installs all the software etc.

You are welcome with AnyDesk to my Test-PC

73 de HB9RYZ
Wolfgang

**Comment by HB9RYZ** [comment]
I found the error in the config.toml file - there were one " missing.
It works now again with "Accelerator=none" and "opencl" :-)

And FT8 works now :-)

![image](https://github.com/Steven9101/PhantomSDR-Plus/assets/70882661/37f081fb-74e5-4c17-b754-800dbde9a83a)

**Comment by HB9RYZ** [comment]
It would be great to use the middle wheel of the mouse to move the freq. from left to the right in order to change the freq. easy and listen and to move to whole waterfall, click into the waterfall and move it than - like in Flexradio SmartSDR.

![image](https://github.com/Steven9101/PhantomSDR-Plus/assets/70882661/aaff684b-b8de-4700-b0b9-1006819cac2a)

**Comment by HB9RYZ** [comment]
It would be also great to use the **"label"** function in the Waterfall as in WebSDR. To mark some broadcast stations or freq. for common QSOs in the Ham-Community.

![image](https://github.com/Steven9101/PhantomSDR-Plus/assets/70882661/131e0091-7210-43d2-91de-5b480fc0a1c0)

**Comment by Steven9101** [comment]
Yea the idea is good, with the frequency i mean you can scroll the frequency input field but i know what you mean like on websdr. What exactly do you mean with the waterfall?

**Comment by HB9RYZ** [comment]
you click with mouse somewhere in the waterfall, and move with the mouse the whole waterfall to the right or to the left. The used freq. will stay as it is - just the waterfall moves. It's not easy to describe - I can show you this behavior on my Flexradio 6700 SmartSDR Interface.

**Comment by Steven9101** [comment]
But when dragging the waterfall its exactly like you described isnt it? Or do you mean the frequency should change when dragging but stay at the same position as it was before but now with the new waterfall

**Comment by HB9RYZ** [comment]
the frequency remains stationary but the entire waterfall moves but the frequency label on the X-axis shifts to the left or right

**Comment by Steven9101** [comment]
Yea but now its basically like you describe it
Like when zooming in to 5mhz and then dragging it shifts to left or right and the frequency stays on 5mhz even if you dont see 5mhz

**Comment by HB9RYZ** [comment]
the best would be to move the freq. with the mouse wheel - this is very convenient

**Comment by Steven9101** [comment]
But dont you like the scrolling on the frequency digits?

**Comment by HB9RYZ** [comment]
the scrolling with the frequency digits are ok, almost the only way to tune exactly - but to move the freq. up and down with the wheel in the mouse would much more easier and user friendly

**Comment by HB9RYZ** [comment]
The NB function does not work. I have an electronic fence from my farmer next to my house. If I press NB, nothing will happen and I still can hear the fence and I see the horizontal lines.

**Comment by Steven9101** [comment]
I also have a fence but its not always on and i can mostly take it out by using vertical polarization but taking it out with Nb is a hard task because its nearly impossible because the lines are perfectly straight and just override signals that are underneath

**Comment by HB9RYZ** [comment]
Hello - any News or Code for the Phantom SDR Plus and RX-888?
I would be very happy, to get the code for the GUI where the waterfall goes from the buttom to the top.
73 de HB9RYZ, Wolfgang

**Comment by HB9RYZ** [comment]
Hello - I was trying to start PhantomSDR Plus, but I will always get the error message "Could not find or open bootloader".
How can I fix this?
73 de HB9RYZ, Wolfgang

**Comment by Steven9101** [comment]
I will close this as you opened another one, and this seems to be done
